version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./data:/data/test.local
      - ./logs/nginx:/var/log/nginx
      - phpsocket:/var/run
    networks:
      - app-network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./data:/data/test.local
      - ./logs/php:/var/log/php
      - phpsocket:/var/run
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  phpsocket:



#services:
#  nginx:
#    image: nginx:stable
#    container_name: nginx_cont
#    ports:
#      - "80:80"
#    volumes:
#      - './nginx/config:/etc/nginx/conf.d'
#      - './src:/var/www/html'
##    networks:
##      - app-network
#
#  #Контейнер с PHP-FPM
#  app:
#    build:
#      context: ./fpm
#      dockerfile: Dockerfile
#    image: myapp/fpm
#    container_name: php_cont # имя контейнера после запуска
#    ports:
#      - "9000:9000"
#    volumes:
#      - './fpm:/usr/local/etc/php'
#      - './src:/var/www/html'
    # мы можем создать для контейнеров внутреннюю сеть
#    networks:
#      - app-network
#
#  mysql:
#    image: mysql:stable


#Docker Networks
#networks:
#  app-network:
#    driver: bridge

