version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./data:/data/test.local
      - ./logs/nginx:/var/log/nginx
      - "phpsocket:/var/run/php-fpm"
    networks:
      - app-network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./data:/data/test.local
      - ./logs/php:/var/log/php
      - "phpsocket:/var/run/php-fpm"
    networks:
      - app-network
#    depends_on:
#      - redis
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  redis:
    image: redis:alpine
    container_name: redis
    hostname: 'redis'
    expose:
      - 6379
    networks:
      - app-network
  memcached:
    image: memcached:1.6.17-alpine
    container_name: memcached
    command: ["-m", "2048"]
    expose:
      - 11211
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  phpsocket:
