version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./data:/data/test.local
      - ./logs/nginx:/var/log/nginx
      - "phpsocket:/var/run/php-fpm"
    networks:
      - app-network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./data:/data/test.local
      - ./logs/php:/var/log/php
      - "phpsocket:/var/run/php-fpm"
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    logging:
      driver: none
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  phpsocket:
